# Generated by Django 4.2 on 2023-11-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('biography', models.TextField(max_length=20000)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
