# Generated by Django 4.2 on 2023-11-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_birth_date_alter_book_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='books.author'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=20000)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='books.book')),
            ],
        ),
    ]
